//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEmprego_Wth_MemberShip_And_mvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        public Anuncio()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> startPub { get; set; }
        public Nullable<System.DateTime> finishPub { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> publish_up { get; set; }
        public Nullable<System.DateTime> publish_down { get; set; }
        public string UrlImg { get; set; }
        public string Conteudo { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> Modified_by { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Lang { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> tipoAnuncio { get; set; }
    
        public virtual language language { get; set; }
        public virtual Local Local { get; set; }
        public virtual Recrutador Recrutador { get; set; }
        public virtual Recrutador Recrutador1 { get; set; }
        public virtual StatusVaga StatusVaga { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual TipoAnuncio TipoAnuncio1 { get; set; }
    }
}
