//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEmprego_Wth_MemberShip_And_mvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Anuncio { get; set; }
        public int Applied_by { get; set; }
        public Nullable<System.DateTime> Applied { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Candidato Candidato { get; set; }
        public virtual StatusApplication StatusApplication { get; set; }
        public virtual Anuncio Anuncio1 { get; set; }
    }
}
