//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEmprego_Wth_MemberShip_And_mvc5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalEmpregoContextDB : DbContext
    {
        public PortalEmpregoContextDB()
            : base("name=PortalEmpregoContextDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Candidato> Candidatoes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Recrutador> Recrutadors { get; set; }
        public virtual DbSet<StatusApplication> StatusApplications { get; set; }
        public virtual DbSet<StatusVaga> StatusVagas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Anuncio> Anuncios { get; set; }
        public virtual DbSet<TipoAnuncio> TipoAnuncios { get; set; }
    }
}
