//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEmprego_Wth_MemberShip_And_mvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusApplication
    {
        public StatusApplication()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int Id { get; set; }
        public string status { get; set; }
        public bool isSelected { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
    }
}
